### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by Lucaskyy** [RohitVermaOP/build-tools-android#1]
Hi there. I'm trying to compile this on Ubuntu, but I'm having some issues with compiling.

I installed the x86_64 Android NDK,
set `ARCH` in `CMakeLists.txt` to `x86-64`,
```cmake
set(ARCH "x86-64")
```
set `NDK_TOOLCHAIN` in `build.sh`
```sh
NDK_TOOLCHAIN=$HOME/AndroidSDK/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64
```
and ran the build script.
Everything goes well, but then I get these errors:
```
In file included from $HOME/build-tools-android/src/aidl/aidl_language_l.ll:24:
$HOME/build-tools-android/src/aidl/aidl_language_y.yy:36:13: error: non-constant-expression cannot be narrowed from type 'unsigned int' to 'int' in initializer list [-Wc++11-narrowing]
    .line = begin.begin.line,
            ^~~~~~~~~~~~~~~~
$HOME/build-tools-android/src/aidl/aidl_language_y.yy:36:13: note: insert an explicit cast to silence this issue
    .line = begin.begin.line,
            ^~~~~~~~~~~~~~~~
            static_cast<int>( )
$HOME/build-tools-android/src/aidl/aidl_language_y.yy:37:15: error: non-constant-expression cannot be narrowed from type 'unsigned int' to 'int' in initializer list [-Wc++11-narrowing]
    .column = begin.begin.column,
              ^~~~~~~~~~~~~~~~~~
$HOME/build-tools-android/src/aidl/aidl_language_y.yy:37:15: note: insert an explicit cast to silence this issue
    .column = begin.begin.column,
              ^~~~~~~~~~~~~~~~~~
              static_cast<int>( )
3 warnings and 2 errors generated.
```
If I do what the `note:` says, I get the same error in `aidl_language_l.ll` instead.
This doesn't seem right, so hence I'm reporting this here.

Do you have a fix for this, or did you not have this issue?

**Comment by Lucaskyy** [comment]
As for the `src/` directory, I unzipped the `src.zip` inside of this repository. It seems that either a broken or outdated version of the `src` directory was pushed.

**Comment by Lucaskyy** [comment]
It also seems that the patches from `sdk-tools` aren't applied (not sure if they are needed, though). So I think my assumption above is right (broken or outdated `src.zip`). If that is true, could you please push/update the latest `src.zip`?

**Comment by RohitVermaOP** [comment]
```set(ARCH "x86_64")``` not ```set(ARCH "x86-64")```

**Comment by RohitVermaOP** [comment]
Set Toolchain ```NDK_TOOLCHAIN=$HOME/android-ndk-r23b/toolchains/llvm/prebuilt/linux-aarch64
```

**Comment by Lucaskyy** [comment]
Sadly, this does not solve the issue as I'm getting the same error as described above.

**Comment by RohitVermaOP** [comment]
Which version of ndk you using?

**Comment by Lucaskyy** [comment]
Ah now that you say that, I think I have the wrong NDK installed. I'll install the proper one and let you know if it worked!

**Comment by Lucaskyy** [comment]
Alright. I was on NDK r22 by accident, just installed r23b (`23.1.7779620` to be exact, latest LTS) but sadly enough, still the same problem.

**Comment by RohitVermaOP** [comment]
I'm using this ndk https://github.com/Lzhiyong/termux-ndk
and compiled build-tools on android for android

**Comment by RohitVermaOP** [comment]
And it's successfully compiled

**Comment by RohitVermaOP** [comment]
Currently i haven't pc or laptop
You need to fix it yourself or exclude aidl source to build

**Comment by Lucaskyy** [comment]
I can confirm that doing it with Termux does work, but I did notice that compiling for other architectures didn't work with Termux. That's because you set the right compiler, but didn't set the `ARCH` in `CMakeLists.txt` in `build.sh`. I was able to compile it by only compiling for the architecture I was using (`aarch64`). So the issue is solved.

**Comment by RohitVermaOP** [comment]
Check binarys it's compiled for ```arm64-v8a, armeabi-v7a, x86, x86_64```
And I'm compiled it one by one with setting ARCH ```arm64-v8a, armeabi-v7a, x86, x86_64```

**Comment by RohitVermaOP** [comment]
aapt2 for x86_64 works or not?
